plugins {
    id 'java'
}

allprojects {
    group = 'io.github.inframeshlabs'
    version = '0.1.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    plugins.withId('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(17)
            }
        }

        dependencies {
            testImplementation 'org.springframework.boot:spring-boot-starter-test'
            testImplementation 'io.projectreactor:reactor-test'
            testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }

        tasks.withType(JavaCompile).configureEach {
            options.compilerArgs << '-parameters'
        }
    }

    plugins.withId('io.spring.dependency-management') {
        dependencyManagement {
            imports {
                mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
            }
        }
    }
}
