package com.inframesh.node.dto.worker;

import com.inframesh.node.dto.ChatMessage;
import com.inframesh.node.dto.ChatOptions;
import com.inframesh.node.dto.ToolChoice;
import com.inframesh.node.dto.ToolDefinition;

import java.util.List;

public record WorkerRequest(
        /**
         * Identifies the logical inference session this request belongs to,
         * for Console-managed Worker session affinity. Supplied by a client
         * or generated by Console; null when no session is associated.
         */
        String sessionId,

        List<ChatMessage> messages,
        ChatOptions options,
        List<ToolDefinition> tools,
        ToolChoice toolChoice,

        /**
         * Carried over from {@code RoutingHints.privateData} so a Worker can
         * enforce the same restriction itself (defense in depth). Missing,
         * null, and false are all equivalent — see {@link #isPrivateData()}.
         */
        Boolean privateData
) {

    public WorkerRequest {
        tools = tools == null ? List.of() : List.copyOf(tools);
    }

    public WorkerRequest(List<ChatMessage> messages, ChatOptions options) {
        this(null, messages, options, List.of(), null, null);
    }

    public WorkerRequest(List<ChatMessage> messages, ChatOptions options, List<ToolDefinition> tools, ToolChoice toolChoice, Boolean privateData) {
        this(null, messages, options, tools, toolChoice, privateData);
    }

    public boolean isPrivateData() {
        return Boolean.TRUE.equals(privateData);
    }
}
